### ISSUE TITLE
Hangs when filtering large collections

### ISSUE THREAD

**Issue by cw1934** [rangav/thunder-client-support#1352]
**Describe the bug**
Entering a term to search in the "filter collections" box results in Windows prompting to terminate the app(included screen capture).  I type in 3 characters in the filter box, but only the first shows and then I get the prompt.  After selecting "Keep Waiting", the other 2 letters show up, but no results show in the Collections area, even though there are known matches.  Deleting the 3rd character and reentering it then allowed the search to complete.

![image](https://github.com/rangav/thunder-client-support/assets/62253522/d2d68fd0-ad42-40ea-a26d-6fb3a2f6a75d)

**To Reproduce**
We have a folder with 20 collections.  Collection files total 7.5mb, ranging from 9kb to 2,140kb, with an average of 384kb.  Order of operations described above.

**Expected behavior**
A set of results filtering in real time.  If triggered by each character changed, filtered in real time.  If not by character entered, then returned in less than 3 seconds after pressing "Enter".

**Platform:** 
 - OS: Windows
 - vscode version: 1.82.2
 - extension version: 2.12.3

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
Thanks @cw1934 for reporting the bug, what the max number of requests in a collection?

**Comment by cw1934** [comment]
@rangav Stats Below.  Just to provide some insight, 18 of the 20 collections were provided(as an OpenApi export*) by a 3rd Party we need to integrate with.  We are writing our own REST service with multiple endpoints that will each then call multiple endpoints on the 3rd Party's API, so having them all together is very advantageous.

I was unable to count in the TC UI, and best I came up with was to use Notepad++ to search for "url" in all files in the thunder-tests/collections folder and have included summary below of the counts.

Total # of Requests: 4977
Largest Collection: 1395
Smallest Collection: 6
Average: 249


*-In order to get from OpenApi to ThunderClient, I first imported into Postman.  If there's a way to go straight from OpenApi to ThunderClient that I missed, any guidance would be greatly appreciated.

**Comment by rangav** [comment]
Thanks @cw1934 for sharing info, will look into it.

Yes Thunder Client supports Open API import
https://github.com/rangav/thunder-client-support#import

**Comment by rangav** [comment]
This bug is fixed in `v2.13.1`. Please test and let me know your feedback.

**Comment by cw1934** [comment]
@rangav We still experience the "not responding" message as before.  I am testing this in v2.13.4.

We did notice that performance is somewhat improved if we paste in the complete term instead of typing it in character by character....but still get the error message in both cases.

**Comment by rangav** [comment]
Thanks for testing and feedback. What is the configuration of the PC - RAM and CPU?

Will research and see how we can improve further.

**Comment by cw1934** [comment]
- Processor
   - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   1.38 GHz
- Installed RAM
   - 16.0 GB (15.4 GB usable)
- System type
   - 64-bit operating system, x64-based processor
- Pen and touch
   - No pen or touch input is available for this display

**Comment by rangav** [comment]
Thanks for sharing PC configuration info.
