### ISSUE TITLE
undo-function does not work

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1387]
**Describe the bug**
Hi Ranga, 

the undo-function does not work in TC. 
When I want toundo (ctrl + z/strg + z) my input, it does not have any effect. 

**To Reproduce**

1. Typ something in the URL or in some value-field
2. Press ctrl + z
3. the input stays the same

**Expected behavior**
The field deletes the input and replaces it with the earlier value.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.83.1
 - extension version: 2.14.1

**Are you using the free version/paid version/trial:**
paid

**Comment by rangav** [comment]
Hi @erwinmoretz thanks for reporting the bug, will fix in the next update

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.

**Comment by erwinmoretz** [comment]
Hi Ranga, 

for me the bug is not fixed. Nothing happens, when i try to undo my input. 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/b9994bad-7c31-497b-8d31-61fe88ecc663)

**Comment by rangav** [comment]
HI @erwinmoretz I have tested now again on Windows it's working for me.

Can you type some new text and then use Ctrl + z

Can you share any video recording of the bug.

**Comment by rangav** [comment]
May be try uninstall and reinstall the extension, sometimes this might work.

**Comment by rangav** [comment]
@erwinmoretz do you still have this issue?

**Comment by rangav** [comment]
relared issue #1397

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.15.3`

https://github.com/rangav/thunder-client-support/releases/tag/v2.15.3

Please test and let me know your feedback.

**Comment by erwinmoretz** [comment]
Hi Ranga, 
the bug is fixed for me with Version 2.15.3.

Thank you!

**Comment by rangav** [comment]
Thanks @erwinmoretz  for the confirmation

**Comment by rangav** [comment]
Hi @erwinmoretz need help from you.

Your colleague seems have issue with CLI running slow in CI and CD

https://github.com/rangav/thunder-client-support/issues/1399

Do you have same issue?

**Comment by erwinmoretz** [comment]
Yes, we have noticed the same behavior. 

local the collection runner is much faster then in CI/CD.

**Comment by rangav** [comment]
Thanks for confirmation, Will look into it.
