### ISSUE TITLE
Local Caddy with Https not working "Couldn't resolve the hostname to an IP address"

### ISSUE THREAD

**Issue by BilalBudhani** [rangav/thunder-client-support#1465]
**Question:**

Hello, I'm running the Caddy server locally to proxy a project with multiple subdomains. 

While I'm able to open Caddy configured domain `project.localhost` in the browser and via `curl` in the terminal. However, I'm unable to query it via Thunder Client. 

I get the following error 
<img width="632" alt="image" src="https://github.com/rangav/thunder-client-support/assets/1650995/cd2f800e-1d04-45d8-a6ea-59015a4fecdf">

I tried changing the underlying `http-library` as recommended in other issues but no success 

<img width="464" alt="image" src="https://github.com/rangav/thunder-client-support/assets/1650995/1fcd1c09-397d-4220-928a-2fbe8e78b48a">

What am I missing? 

**Are you using the free version/paid version/trial:**

**Comment by BilalBudhani** [comment]
Thanks for response @rangav 

I'm actually sending requests to a subdomain like `api.project.localhost` which is why I can't send it via `0.0.0.0` or any other local IP.

**Comment by rangav** [comment]
@BilalBudhani  I have implemented a fix in `v2.17.2`, can you please test it and let me know if it's working or not?

How to use
1. Update Extension to `v2.17.2`
2. From Vs Code Settings Enable setting `Preview Features` ( see screenshot below)
3. Change `Http Libary` to Axios in Vs Code setting
4. Now test the localhost URL and let me know your feedback.

<img width="703" alt="Screenshot 2024-01-31 at 16 25 07" src="https://github.com/rangav/thunder-client-support/assets/8637550/3535f408-3361-4de8-bb4f-8097767881e5">

**Comment by BilalBudhani** [comment]
Hey @rangav I appreciate you looking into this issue. I tried following all the above mentioned steps but unfortunately, the problem persists. 

<img width="389" alt="image" src="https://github.com/rangav/thunder-client-support/assets/1650995/613a430f-c1cc-46bc-a457-de14b5fdb4cd">

<img width="524" alt="image" src="https://github.com/rangav/thunder-client-support/assets/1650995/50fa68e7-17fe-4b3f-a071-701d89cd2bb2">

**Comment by rangav** [comment]
Thanks for testing, can share logs data in output window if possible

<img width="900" alt="Screenshot 2024-02-01 at 10 24 51" src="https://github.com/rangav/thunder-client-support/assets/8637550/8a38f403-ccbe-4070-8e2d-38d0a41261e0">

**Comment by BilalBudhani** [comment]
Here it is 

```
---------------- Running Request: ----------------
Environment Used: development (Active)
Request Url: https://api.project.localhost/v2/path
Method: GET
Request Headers:
{
  "Accept": "*/*",
  "User-Agent": "vscode",
  "x-api-key": "[redacted]"
}
Request Body:
{
  "uuid": "[redacted]"
}
```

I guess there ain't much to work with

**Comment by rangav** [comment]
I have updated the code again to fix localhost issues in update v2.17.5

Can you test again with `axios` and `got` and let me know your feedback.

You can do the DNS Test command to verify the IP used
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.5

Please test and let me know your feedback.

**Comment by rangav** [comment]
Closing this issue let me if you still have any problems
