### ISSUE TITLE
Connection was refused by the server.

### ISSUE THREAD

**Issue by berkobob** [rangav/thunder-client-support#170]
**Describe the bug**
I've written a very simple REST JSON server in Dart using Shelf. I can make requests via a browser or Postman but when using Thunder Client I get "Connection was refused by the server."

**To Reproduce**
http://127.0.0.1:8081/
http://localhost:8081/

**Expected behavior**
I would expect "200 Server running"

**Platform:** 
 - OS: Mac OS 11.3.1
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Solution:**

**Comment by rangav** [comment]
Hi @berkobob thanks for reporting the issue.

- Can you share a screenshot, with request and response.
- Are you using any proxy?
- Is the request redirecting http to https in browser?

**Comment by berkobob** [comment]
Screenshot attached.

I'm not using a proxy and it's all http (no https)

**Comment by rangav** [comment]
Thanks @berkobob can you also share screenshot of headers tab, to see what headers are sent.

**Comment by berkobob** [comment]
[image: Screenshot 2021-05-23 at 09.10.18.png]

**Comment by rangav** [comment]
I think it could be issue with headers, as its working in browser.

Can you try below and see if its working or not.

1. Remove content-type header and test it.

2. please copy the url that is working in browser and import as curl into thunder client and test it.
![image](https://user-images.githubusercontent.com/8637550/119256859-9dc24d80-bbba-11eb-960e-bd4d36887fa8.png)

**Comment by berkobob** [comment]
Are we on the same version? I don't know what you pressed to get that menu? If you look at this screenshot, I was able to find "Import Curl" by pressing on the icon I've circled. I then entered the url which was successful in the browser. 

<img width="1071" alt="Screenshot 2021-05-23 at 13 36 25" src="https://user-images.githubusercontent.com/6568107/119260790-4d53eb80-bbcc-11eb-9cf0-385a1fae45b0.png">

However, all this did was create your default query as you can see in this screenshot

<img width="1680" alt="Screenshot 2021-05-23 at 13 37 07" src="https://user-images.githubusercontent.com/6568107/119260891-c6ebd980-bbcc-11eb-8a50-b078d83e0e08.png">

Also, if you look at the bottom in the terminal you will see a successful curl command

**Comment by rangav** [comment]
Open your localhost url - http://127.0.0.1:8081/ in the browser, and **copy as cURL** from network tab

![image](https://user-images.githubusercontent.com/8637550/119261045-6c9f4880-bbcd-11eb-906f-f04506e291b1.png)

**Comment by berkobob** [comment]
Found it! Thanks. So this is what was copied

```
curl 'http://localhost:8081/' \
  -H 'Connection: keep-alive' \
  -H 'Cache-Control: max-age=0' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed
```

but no luck. Here is the screen shot after importing the curl command:

<img width="1680" alt="Screenshot 2021-05-23 at 14 52 07" src="https://user-images.githubusercontent.com/6568107/119263353-9741cf00-bbd6-11eb-9853-c7249c8c8087.png">

**Comment by rangav** [comment]
is it working on the browser? can you share the browser screenshot showing that the url is working.

**Comment by berkobob** [comment]
Yes, it works on all my browsers, cURL, Postman etc.  Here's a browser screenshot 

<img width="440" alt="Screenshot 2021-05-23 at 15 16 45" src="https://user-images.githubusercontent.com/6568107/119264210-1684d200-bbda-11eb-96b1-f033bd0992b1.png">

**Comment by rangav** [comment]
can you also share postman screenshot 

Also stop your local server and restart again.

**Comment by berkobob** [comment]
I've restarted the server but it made no difference. Here is the Postman screenshot

<img width="1274" alt="Screenshot 2021-05-23 at 15 29 22" src="https://user-images.githubusercontent.com/6568107/119264603-cc045500-bbdb-11eb-917d-d2b91b23b9d9.png">

**Comment by rangav** [comment]
Cant find where is the problem. Anyway thanks for sharing the screenshots, if I find a solution, i will get back to you.

**Comment by hygsani** [comment]
same thing happened to me when i'm using PHP built-in server with this command => php -S localhost:8000 -t public/
after i changed the 'localhost' to '0.0.0.0' the message gone and the requests working

**Comment by rangav** [comment]
thats good to know. you finally found the solution :)

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed.

**Comment by berkobob** [comment]
That wasn't me nor does that solution work for me. Please re-open. Thank you.

**Comment by rangav** [comment]
@berkobob re-opened it, thought it was you.

**Comment by hygsani** [comment]
i haven't use dart, but i guess the problem is on 'localhost'
try change the 'localhost' to '0.0.0.0' in dart server listener (shelf_io.serve(params))

```
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart' as shelf_io;

void main() async {
  var handler =
      const Pipeline().addMiddleware(logRequests()).addHandler(_echoRequest);

  var server = await shelf_io.serve(handler, '0.0.0.0', 8080);

  // Enable content compression
  server.autoCompress = true;

  print('Serving at http://${server.address.host}:${server.port}');
}

Response _echoRequest(Request request) =>
    Response.ok('Request for "${request.url}"');
```

**Comment by rangav** [comment]
also there are 2 other useful links on web related to this issue, see if any of them works?

https://github.com/dart-lang/http/issues/233
https://stackoverflow.com/questions/23691105/dart-servers-refusing-connection-in-local-network/23691467

**Comment by berkobob** [comment]
It worked!! Thanks so much. I just changed my hostname from localhost to 0.0.0.0 and it works perfectly. Thanks again.

**Comment by rangav** [comment]
Thanks @berkobob for confirmation 

and Thanks to @hygsani for finding the solution.

**Comment by JoelBonetR** [comment]
Same here, any request to localhost:port ends up in a "Connection was refused by the server." error message.

I was setting up a Node Express server, without athentication nor authorization services in the middle, nor SSL, just http get request. If I run localhost:5000 on the browser I get the expected JSON.

**Comment by marlonbrum** [comment]
Just to add something to the case, here I was using php builtin server , with "php -S localhost:8000 -t public", and was getting the same error. After I changed the command to "php -S 127.0.0.1:8000 -t public"  it worked. It works when i call http://127.0.01/api" AND "http://localhost/api"

**Comment by s850042002** [comment]
Here's my finding to those are using golang gin. I got the same error no matter I use
`router.Run(":8080")` or `router.Run("0.0.0.0:8080")`.
Only `router.Run("127.0.0.1:8080")` works. But I guess it's for local testing only.

**Comment by EASTF0X** [comment]
Hello everyone!

I had the same issue and none of the above mentioned solutions worked for me... I was close to desperation! 😄 

Instead of using 'localhost' or your local ip address try : **[::1]** <-- yes use with brackets []! (of course this is also your local ip address, but yea... I don't understand why this worked for me but not 192.168.xx.xx ...)

**Comment by fijiwebdesign** [comment]
> Hello everyone!
> 
> I had the same issue and none of the above mentioned solutions worked for me... I was close to desperation! 😄
> 
> Instead of using 'localhost' or your local ip address try : **[::1]** <-- yes use with brackets []! (of course this is also your local ip address, but yea... I don't understand why this worked for me but not 127.0.0.1 ... apparently my setup is ipv6 only ?)
> 
> ![image](https://user-images.githubusercontent.com/92914539/160245279-bcdb02ee-bdce-4899-8fad-4bfe8422b00d.png)

It appears that using `localhost` in ThunderClient doesn't resolve correctly to the ipv6 address **[::1]** if the server is attached to that address. 

The issue is on some machines using just a port to attach your server will attach to **[::1]** address automatically. 
The browsers will correctly resolve **localhost** to **[::1]**
ThunderClient resolves **localhost** to **127.0.0.1**

** If we could see the ThunderClient source we could contribute a fix :) **

Mitigations are to use ip4v address as your server host address. 

For my example with fastify

```
const addr = await fastify.listen(PORT, '127.0.0.1')
    console.log('Server running at ' + addr)
```

with Express

```
app.listen(port, '127.0.0.1', () => {
  console.log(`Example app listening on port ${port}`)
})
```
This way you can use `localhost` in ThunderClient. 

You can also use **[::1]** in the URL for Thunderclient direclty as @EASTF0X  mentioned. 

Example

```
http://[::1]:5050/api
```

Or better you could create an env var for `host` and make the value `[::1]` for local development

```

/*
Env: Local Dev
host [::1]

Env: Production
host myapi.com
*/

http://{{host}}:5050/api
```

That way you can switch the host based on enabled env (development, production etc.) without fiddling with localhost resolution.

**Comment by rangav** [comment]
Hi @fijiwebdesign 

I am using below library for http requests
https://github.com/sindresorhus/got

if you find any option to fix this, let me know.

**Comment by rangav** [comment]
they dns lookup version to configure
https://github.com/sindresorhus/got/blob/dbbd31777b3299ceb0db99798453e01ab8e597b1/documentation/2-options.md#dnslookupipversion

**Comment by fijiwebdesign** [comment]
@rangav got only supports one ip address at a time. So if there are multiple IPs you'd have to make multiple `got()` requests. That would mean each request would use up the request limit's before trying the next. You could set the request limit to 1 and try the next ip in succession but that would make the other configs for  `options.retry` useless. 

`options.retry` has extensive logic for retry timeouts, delay and backoff  so best to keep it while trying each ip. https://github.com/sindresorhus/got/blob/dbbd31777b3299ceb0db99798453e01ab8e597b1/documentation/7-retry.md

The following will keep `options.retry` configs but rotate through the IPs returned from DNS while making only one dns request per `got()` request. 

```
import got, { Options } from 'got'
import dns from 'dns'

async function fetchUrl(url, options) {
  let dnsEntries
  let fetchCount = 0
  const host = (new URL(url)).hostname
  const dnsLookup = (host, options, cb) => {
    if (dnsEntries) {
      fetchCount++
      const nextEntry = dnsEntries[fetchCount % (dnsEntries.length)]
      return cb(null, nextEntry.address, nextEntry.family)
    }
    options = {
      ...options,
      all: true
    }
    dns.lookup(host, options, (err, addresses) => {
      if (err) throw err
      dnsEntries = addresses
      dnsLookup(host, options, cb)
    })
  }
  const res = new Promise(resolve => {
    dnsLookup(host, { all: true }, async (err, addresses) => {
      const retryLimit = options?.retry?.limit || 3
      const res = await got(url, undefined, new Options({
        ...options,
        dnsLookup,
        retry: {
          ...options?.retry,
          ...{
            limit: retryLimit
          }
        }
      }))
      resolve(res)
    })
  })
  
  return res
}

fetchUrl('http://localhost:5050/trades')
  .then((res) => console.log(res.body))
  .catch(err => console.log('Error', err.message))
```

So if you did one `got('localhost')` and `retry.limit=3` it would do. 

```
dns request -> 2 ips [ipv4, ipv6]
got(ipv4) -> dns fail
got(ipv6) -> example network fail
retry got(ipv4) -> dns fail
retry got(ipv6) -> success
```

**Comment by josephcozad** [comment]
Hello. I have the exact same error. However I get this error not when accessing localhost or 0.0.0.0. I get this error trying to send a request to a server within our company's domain. Like the above, if I use a browser or Postman, no issue. The other thing that's odd is that I had this issue one day, then the next it was gone, then the next day it reappeared. I didn't do anything I can think of that would suggest a "clearing" of history/cache. Computer hasn't been restarted. I have tried closing and restarting VSCode but that hasn't helped.

Mostly I wanted to make sure that you guys knew that this isn't relegated to localhost. At lease for me I get the same issue trying to access any server on our company network with this plugin in VSCode and it's spotty. Also I have been using Thunder Client for over a year without issue. Only in the last couple of days has this appeared for me. My VSCode is version 1.66 and Thunder Client is v1.16.0. I'm on a Windows 10 OS.

**Comment by rangav** [comment]
@josephcozad, @fijiwebdesign  thanks for the feedback, will research further on this issue and get back to you.

**Comment by Kaviah** [comment]
> 

Hi, I´m having the same issue but I couldn´t solve with your solution, can you help me to find out if I did right? Thank you!
![erro-thunder-erro](https://user-images.githubusercontent.com/27789600/178110071-11e995b0-f3f0-46e8-bcd9-16d32d7e7a4a.png)
![erro-thunder-index](https://user-images.githubusercontent.com/27789600/178110073-a846b9c7-6508-4b7e-88e3-f10a32ec2263.png)

**Comment by rangav** [comment]
@Kaviah did you try `http://localhost:3000/users`?

**Comment by rangav** [comment]
@Kaviah did you try `http://localhost:3000/users`?

**Comment by Alynva** [comment]
I think that this is still an open issue. For me, it worked using ipv6 `[::1]` as host on Thunder, but having to explain this problem to every coworker its not great. The usage of Thunder shouldn't force me to change my servers running in `localhost` to run on `127.0.0.1` or something else... I know that the source problem may come from [got](https://github.com/sindresorhus/got), but the message `Connection was refused by the server.` (that isn't clear at all) is a Thunder issue and it is still happening...

**Comment by rangav** [comment]
@Alynva thanks for reporting.

got library is causing lot of issues around the connection refused, might move to `axios`.

if you are using `node` for development. can you confirm your localhost address is accessible using with `axios` library without any issues?

**Comment by Alynva** [comment]
> @Alynva thanks for reporting.
> 
> got library is causing lot of issues around the connection refused, might move to `axios`.
> 
> if you are using `node` for development. can you confirm your localhost address is accessible using with `axios` library without any issues?

I'll try to create an reproducible repo comparing `got` and `axios` behavior, but I can't promise it will be right now

**Comment by rangav** [comment]
@Alynva simple url access test is enough just to confirm its working or not. 

ok let know when you done the testing with axios.

**Comment by rangav** [comment]
Hi all, we add new http library option for `axios` in v1.18.3. please update test it and let me know your feedback

<img width="837" alt="http" src="https://user-images.githubusercontent.com/8637550/184552594-606c3ccc-850d-4dad-88f2-fc024f963f92.png">

See features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

**Comment by vifeng** [comment]
http library option for axios is not working on my end. best option is [::1].  tell me if you need me to provide something and what

**Comment by Kaviah** [comment]
*I've noticed my lack of attention to that little detail... Sorry
about that... And thank you for your reply!*

*Sandra Ferla*
+55(75)99213-4011
www.kaviah.com
canal no Telegram <https://t.me/kaviah_com>






Em sáb., 9 de jul. de 2022 às 11:33, Ranga Vadhineni <
***@***.***> escreveu:

**Comment by belachkar** [comment]
Resolved by changing the **backend server address**:
From **localhost** to **127.0.0.1** or **0.0.0.0**.

**Comment by marckregio** [comment]
Resolved on my end by changing http://localhost:3000 to [::]:3000. I am just curious why it has to like this.
![Screenshot 2022-11-20 at 11 10 12 AM](https://user-images.githubusercontent.com/5000810/202880866-6079e218-ee66-4748-bbb7-b49629e1fec0.png)

**Comment by rangav** [comment]
@marckregio it is related to ipv6 address 

Read this
https://stackoverflow.com/a/40189197/4035948

**Comment by hungtcs** [comment]
Hello, I have the same problem, I use nestjs created a server and listen host `0.0.0.0`. Then copy curl from browser devtool and import into thunder-client.

I tried ipv6 still not working.

```shell
curl 'http://127.0.0.1:3001/swagger-json' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: AGL_USER_ID=fd053bc9-afdc-4702-a5ac-0620bc315fd5; Hm_lvt_a8b32306ce37093997d8923fa6bcda22=1662542692; login_region=; login_domain=; csrftoken=yLcM6XgrDSveOC5oO3HNyfXcKJucP495; Hm_lvt_a0ff3b9a602190befef9ba3befd37f57=1667290576,1668656041,1669261615' \
  -H 'DNT: 1' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```

![image](https://user-images.githubusercontent.com/11692935/205004319-48aad9ed-b87a-4559-87ef-66966e9c2203.png)

Test the curl command in terminal is working well:

![image](https://user-images.githubusercontent.com/11692935/205004855-e7feb45e-e702-4357-9015-93cd7b571e3f.png)

**Comment by steelvelveteen** [comment]
Hi all, tried all the solutions provided here. My Thunder Client just stopped working. I had to download Postman to test it works just fine on Postman. Neither alternatives to localhost have worked for me. Please keep issue open

**Comment by rangav** [comment]
@steelvelveteen can you please screenshot of the request and error

**Comment by steelvelveteen** [comment]
![image](https://user-images.githubusercontent.com/23939091/207859837-31a1e082-a9ae-4f0e-bc25-862b403a18b7.png)

**Comment by steelvelveteen** [comment]
And my headers
![image](https://user-images.githubusercontent.com/23939091/207860126-4795e224-a21b-40ca-8b99-daaa3d62f52a.png)

**Comment by steelvelveteen** [comment]
Thanks rangav, I tried all the possible solutions on this page and none work. Connection Refused

**Comment by rangav** [comment]
> Thanks rangav, I tried all the possible solutions on this page and none work. Connection Refused

**Did you try this option?**

use `localhost:56752` and enbale `preview features` settings

![image](https://user-images.githubusercontent.com/8637550/207861492-a94f62c5-0b4e-45ca-8c74-78261ea017a7.png)

**Comment by steelvelveteen** [comment]
Yes, I did. Combinations of [::1] , 127.0.0.1, 0.0.0.0 with got, axios, preview features and nothing yet.

**Comment by rangav** [comment]
what backend application is yours? is it `node`?

**Comment by steelvelveteen** [comment]
It's an ASP.NET Core 2.2 application

**Comment by rangav** [comment]
thanks for sharing, will try and see if i can re-produce the issue here.



> It's an ASP.NET Core 2.2 application, and it was working until a couple hours ago. All that has changed is that I restarted my computer.

Did you check its not a proxy issue?

**Comment by steelvelveteen** [comment]
Not sure about that. I am using a VPN, without it there would  be no access at all to the api I'm querying. But this hasn't been an issue until today. All queries I have saved in the extension fail, complex, simple queries, all of them.

**Comment by hungtcs** [comment]
@steelvelveteen Did you check this vscode setting?

![image](https://user-images.githubusercontent.com/11692935/208010511-388276bd-bfb2-459d-a267-9102057ad916.png)

**Comment by marifcelik** [comment]
I was facing the same problem. in my case problem solved when I use only port in app.listen function in express app
```js
app.listen(PORT, () => {
    // some codes
}) // like this
```

**Comment by huncholane** [comment]
If you're using npm edit the dev script to have --host at the end

**Comment by myleftshoe** [comment]
replacing localhost with `[::1]` worked for me too  `http://[::1]:5173/`. I don't know where the problem lies but the ability to use `localhost' is needed - especially if yr cutting and pasting

**Comment by dxps** [comment]
I was resuming evaluating this client and guess what, got into this issue straight away. :facepalm: 

Based on the aforementioned ideas, I tried all of these and nothing worked:
- using `localhost` or `127.0.0.1` or `[::1` as the address (not the scheme or port, ofc)
- no proxy is set at VSCode level
- using either `got` or `axios` clients

Of course, it works:
- using generated `cURL` code
- in Postman

Context:
- VSCode ver. 1.75.1
- Thunder Client ver. 2.4.1
- OS: Pop!_OS 22.04 LTS

Any other ideas, please?

**Comment by Dfamilia** [comment]
1. if you are using WSL on Windows use [::1] or [::] instead of localhost in the address bar. Example [::1]:3000/api/v1 .
2. Another option is to use the PowerShell instead of the WSL terminal.
3. You can also move your project directory to the Linux file system (~/home)
