### ISSUE TITLE
Thunder client Response file size issue

### ISSUE THREAD

**Issue by dragonH** [rangav/thunder-client-support#262]
**Describe the bug**
Thunder client page become blank

**To Reproduce**

After process large query with thunder client

Thunder client page come to blank and cant initialize

**Expected behavior**
Thunder client page show as normal

**Platform:** 
 - OS: Win10 21H1 19043.1083 with WSL (Ubuntu 18.04)
 - vscode version: 1.57.1
 - extension version: v1.6.1

**Solution:**
After checking the dev tool

it shows that the thunder client meet some error when initialize

i check the db file that using by thunder client

the size of it comes about 550 MB

try to remove it (by renaming)

and restart vscode and thunder client

it become normal and initialize successfully

and it create a empty db file there

i think that might some bugs when db size is too big ?

![image](https://user-images.githubusercontent.com/18332044/125185873-c4674100-e259-11eb-9d6c-31db90afffe8.png)
![image](https://user-images.githubusercontent.com/18332044/125185887-cfba6c80-e259-11eb-9f1a-650f1a8a3dd3.png)
![image](https://user-images.githubusercontent.com/18332044/125185932-085a4600-e25a-11eb-917d-c99eff39f8ec.png)

**Comment by rangav** [comment]
Hi @dragonH thanks for reporting, how big is the response? Size?

**Comment by dragonH** [comment]
> Hi @dragonH thanks for reporting, how big is the response? Size?

hi @rangav 

cant remember the exact number

but the requests were all succeed without any error

i can get the the response from the api in thunder client

but after i re-open vscode and thunder client

everything in become blank aith the error pop out

**Comment by rangav** [comment]
Hi @dragonH identified the cause of issue, will fix it in next update

**Comment by dragonH** [comment]
hi @rangav thanks

let me know if anything i can help

**Comment by rangav** [comment]
This is now fixed in v1.8.0, please test and let me know

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

**Comment by dragonH** [comment]
> This is now fixed in v1.8.0, please test and let me know
> 
> see all features released
> https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

hi @rangav 

the issue still

![image](https://user-images.githubusercontent.com/18332044/127005485-30f2dae4-25c6-4ad8-860f-c8985a0b25fa.png)

FYI

there are 137 lines in db file with 546 mb

![image](https://user-images.githubusercontent.com/18332044/127005607-f522640c-bfd7-4c34-83e1-f2abecf2f6ec.png)


my vscode version: `1.58.2`
thunder client version: `1.8.0`

btw

should i reply here or open a new issue for u to trace ?

thanks

**Comment by rangav** [comment]
you can continue here, can you manually delete the responses.db file, and try again.

**Comment by dragonH** [comment]
yes 

manually deleted always works even before the fix release

is the fix is not aim to solve the large db issue ?

**Comment by rangav** [comment]
Earlier it will keep duplicates in the file and removes duplicates, so the file size will be less. Let me know if see the issue again.

**Comment by dragonH** [comment]
hi @rangav 

not sure what is the duplicates you mean

i use the follow code to see if the lines duplicated

```
const fs = require('fs');
const es = require('event-stream');

const dbFilePath = '<db path path>';
const records = [];
let counter = 0;
fs
    .createReadStream(dbFilePath, { encoding: 'utf-8' })
    .pipe(es.split())
    .pipe(es.mapSync((line) => {
        if (line) {
            const lineAsJson = JSON.parse(line)
            records.push(
                {
                    _id: lineAsJson['_id'],
                    modified: lineAsJson['modified'],
                    hashValue: `${lineAsJson['_id']}${lineAsJson['modified']}`
                }
            )
            counter += 1;
            console.log(counter);
        }
    }))
    .on('end', () => {
        console.log(`records length: ${records.length}`);
        console.log(`hashValue length: ${[...new Set(records.map((record) => record['hashValue']))].length}`);
    });
```

the result shows like below

![image](https://user-images.githubusercontent.com/18332044/127023973-0f3cbf36-c867-43e0-b8cd-9902ab0f2bbc.png)

i dont think the data is duplicated

since the modified is differ

**Comment by rangav** [comment]
Yeah that’s right if you 2 records with same _id then they are duplicates. 

When you run the same request multiple times, then it used to create duplicate records in thunderResponses.db file and remove duplicates when you reload vscode next time.

now it won’t create duplicates at all

nothing to do with your code, that’s how db library handles it by default in the extension.

you just use it normally, no change needed from your side.

**Comment by dragonH** [comment]
Mmmmm...

but it seems that it could only solve the issue for now (correct me if I'm wrong😋)

what if i use thunder client for a long time

would this issue appear again with the usage times grows ?

**Comment by rangav** [comment]
It will only keeps recent responses, so won’t happen

**Comment by dragonH** [comment]
how about lots of requests in a short time ?

if this also be handled, i think the issue is solved 🙂

**Comment by rangav** [comment]
Ok got it 👍
