### ISSUE TITLE
copy is not working

### ISSUE THREAD

**Issue by gogoIsComing** [rangav/thunder-client-support#439]
**Describe the bug**
copy option in right click menu is not working in response section

**Platform:** 
 - OS: windows 10
 - vscode version: 1.63.2
 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @gogoIsComing 

the right click menu and copy functionality are provided by vscode, so it could be vscode issue.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback

**Comment by gogoIsComing** [comment]
@rangav i updated the extension to `1.11.1` but it is still not working, when i copy some thing from response section and paste it , it pastes one or more spaces.

**Comment by gogoIsComing** [comment]
@rangav to let you know, i tried to open issue in vscode repo but they wrote in issue page `Issues caused by an extension need to be reported directly to the extension publisher.` so i reported about this issue here, because the copy and paste functionality is working in other parts of vscode.

**Comment by rangav** [comment]
@gogoIsComing I have tested it now on Mac with url https://www.thunderclient.com/welcome

With the context menu, i did copy and paste in another input, its working for me?

Can you let me know if I am missing the steps?

**Comment by gogoIsComing** [comment]
@rangav i am using windows 10 and this is what i am getting : 


https://user-images.githubusercontent.com/33967218/152682373-7cd67427-7525-4ef8-a372-a719b9dcf458.mp4

**Comment by rangav** [comment]
Hi @gogoIsComing cant play the video, it's not loading

**Comment by gogoIsComing** [comment]
Hi @rangav same as me, try to use vpn.

**Comment by gogoIsComing** [comment]
@rangav in video i am demonstrating the problem i have with the extension.

**Comment by rangav** [comment]
Its working now thanks

Strange its working for me on my mac.

Can you do the following

- Open extensions tab, select any extension, that will open extension view page
- then copy and paste any text as you did in video

**Comment by rangav** [comment]
alternative option, try `Ctrl+C and Ctrl+V`

**Comment by rangav** [comment]
Hi @gogoIsComing I just now tested on windows, yes, it's not working as you said. 

I opened up the extension page for C# and tried the copy and paste as you did in video, it's not working.

So, I think it's a vscode bug.

![image](https://user-images.githubusercontent.com/8637550/153000488-17d6ddc0-7789-464e-a6f1-78be53aadad0.png)

**Comment by gogoIsComing** [comment]
Hi @rangav
> So, I think it's a vscode bug.

 yes, it is vscode bug on windows machines.

**Comment by Tahadxbydy** [comment]
I am still getting this error version [v2.21.15] I can't copy, cut or paste from body of request or the response and when I try to paste something in the body it is pasted in the terminal.
