### ISSUE TITLE
Cannot access JSON attribute named "index"

### ISSUE THREAD

**Issue by natethelen** [rangav/thunder-client-support#515]
**Describe the bug**
When working with JSON responses and setting values into environment variables, I cannot access any JSON element that is named "index"

**To Reproduce**
Using the following JSON as an example:
`{
  "totalItems": 1,
  "items": [
    {
      "name": "my name",
      "index": 0
    }
  ]
}`

I can access the name via this selector: `json.items[0].name` but get the following error when trying to use `json.items[0].index`:  "Set Env Failed: Unable to parse left input query"

I have tried:
- json.items[0].index
- json.items[0]."index"
- json.items[0].["index"]
- json.items[0]["index"]

**Expected behavior**
The value of 0 in this example would get set to the specified environment variable

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.65.2
 - extension version: 1.14.0

**Comment by natethelen** [comment]
Same issue with a much simpler response (so you don't think it is because it is in an array):

`{
  "index": 5
}`

Tried:
- json.index
- json."index"
- json.["index"]
- json["index"]
- index
- "index"

**Comment by natethelen** [comment]
The plot thickens...  I have now run into another JSON response that has a similar problem:

`{
  "accountName": "My Account",
  "accountIndex": 0
}`

This works: `json.accountName`, this does not: `json.accountIndex`

**Comment by rangav** [comment]
you can test yourself using this url
https://www.thunderclient.com/t/echo
<img width="1609" alt="Screenshot 2022-03-24 at 21 01 13" src="https://user-images.githubusercontent.com/8637550/160009539-3a2c899a-9037-442f-83c2-a7023de2cb09.png">

**Comment by rangav** [comment]
Thanks @natethelen for reporting the issue, i can reproduce the issue. will fix it asap.

**Comment by natethelen** [comment]
OK, cool!  When using the echo I am not seeing the problem, either.  What did it take for you to reproduce (if you don't mind me asking)?

**Comment by natethelen** [comment]
Looks like it has to do with integer values.  String values work for me

**Comment by rangav** [comment]
Json query is working, but Set Env Var is not working. 

You can test with this url
https://www.thunderclient.com/t/echo

**Comment by rangav** [comment]
only when index value is 0 causing the issue, other values should work fine

**Comment by rangav** [comment]
@natethelen  fixed this bug and published a `pre-release` version `v1.15.0`, so you don't have to wait till release version.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by rangav** [comment]
This bug is is now fixed and published to marketplace, please update to `v1.14.1`

let me know if any feedback

**Comment by natethelen** [comment]
I have upgraded and tested it out.  I am no longer seeing the error but I am still having a problem.  If I do the following:

1. Confirm no environment variable named test_index
2. Run the Request with the "index" value of 0 with a test that sets that value to environment variable test_index (no errors)
3. Check the environment variables and confirm a new environment variable test_index with a value of 0
4. Run another Request where {{test_index}} is in the URL

In this case the place in the URL with 0 should be is blank.  I can confirm by going to the Code Snippet and seeing the substituted URL.  Then I do the following:

1. Go to the environment variables, replace the 0 that is showing there with a 0 I typed from my keyboard, click Save
2. Re-run the Request from step 4 above (it works, and going to the Code Snippet shows the 0 in the right place)

**Comment by rangav** [comment]
@natethelen will verify and get back to you

**Comment by rangav** [comment]
Looks like there is another bug around this, fixed now, will publish in the next update by end of this week.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.14.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

Let me know if any feedback
