### ISSUE TITLE
Localhost is considered to be an invalid url

### ISSUE THREAD

**Issue by Zombobot1** [rangav/thunder-client-support#646]
**Describe the bug**
When accessing localhost the request resolves with an error status and the Invalid URL message appears. 

**To Reproduce**
Run get request for  http://localhost:4000  or use 127.0.0.1 instead of localhost
![image](https://user-images.githubusercontent.com/48030070/177062017-75f5f966-94d7-41c7-b6fc-0290b96cb3e3.png)

**Expected behavior**
It works as it does in postman.
![image](https://user-images.githubusercontent.com/48030070/177062030-bc4542c4-45c1-485c-964d-a6a8ce792dc7.png)

**Platform:** 
 - OS: macos
 - vscode version:  1.68.1
 - extension version: v1.16.5

**Solution:**
I see that it should work according to this [issue](https://github.com/rangav/thunder-client-support/issues/252). 
I found this [workaround](https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967) but didn't test it due to bad DX.

**Comment by Zombobot1** [comment]
Fixed this problem by restarting the server.

**Comment by hashiromer** [comment]
I am having the problem, but it does not resolve upon restarting the server.
