### ISSUE TITLE
OAuth 2 token not being added to the request

### ISSUE THREAD

**Issue by ddg1-vayu** [rangav/thunder-client-support#847]
**Describe the bug**
After a recent update, using an access token in OAuth 2 of Auth tab does not get added to the request or the generated code snippet, causing the request to fail.

Both newly created requests and already saved requests are having this issue.

![image](https://user-images.githubusercontent.com/43469039/196603766-3e6afa94-058e-438f-a00e-f206555b49d6.png)

**To Reproduce**
Create/Use any request with OAuth 2 to reproduce this issue.

**Expected behavior**
The access token added to the Access Token field in the Auth tab should be added to the request and the generated code snippet.

![image](https://user-images.githubusercontent.com/43469039/196603235-1b5dffbd-4182-4da9-9fd3-ffccf735bad2.png)

**Platform:** 
 - OS: Windows 10 Pro (Build 19044.1826)
 - vscode version: 1.72.2 (2022-10-12)
 - extension version: v1.20.0 (2022-10-12)

**Comment by rangav** [comment]
Hi @ddg1-vayu 

- restart vscode  
 
- you need to click `generate token` button  first. Then token will be generated 
- execute request now you should see token sent
- See output window for logs

Currently token is not added to code snippet, will update in the next release

**Comment by rangav** [comment]
Alternatively you can use `Bearer` tab and paste token.

**Comment by ddg1-vayu** [comment]
> Alternatively you can use `Bearer` tab and paste token.
Thanks, tried this and it is working correctly.

Regarding your 1st comment, I use tokens from my database to test APIs. Do I have to regenerate the access token to send requests with OAuth 2? Previously, I just copy-pasted the token and sent the request and that worked perfectly.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v1.20.1`

See release notes here
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1

**Comment by can-I-do** [comment]
it is still not working for me, still have to copy it over to the "bearer" tab

**Comment by rangav** [comment]
@can-I-do its working for me

<img width="1269" alt="Screenshot 2023-01-10 at 13 20 13" src="https://user-images.githubusercontent.com/8637550/211562558-8eea8125-0502-4eea-ab75-eecadb5ac1c8.png">

Can you test with this url `https://httpbin.org/anything` and share screenshot?

**Comment by can-I-do** [comment]
![CleanShot 2023-01-10 at 14 25 38](https://user-images.githubusercontent.com/60129163/211563587-54ccb0ba-2bb6-4436-9bce-307f88c3e46c.png)

**Comment by rangav** [comment]
what version of vscode and extension are you using? try re-start of vscode

**Comment by can-I-do** [comment]
good old restarting -.- I restart (or rather close and start it again) multiple times per day... don't  know what this was.
Very sorry, it is working!!! Thx for the support
